### PR TITLE
Continue hypsometries

### PR DESCRIPTION
**Pull request by fmaussion**
This is not going to pass until https://github.com/OGGM/oggm/pull/476 is merged

### CODE REVIEW

**Comment by fmaussion** [comment]
This finishes the work started by @jlandmann  in https://github.com/OGGM/rgitools/pull/2. 

It relies more heavily on OGGM and reproduces the exact same files as RGI does.

**Comment by jlandmann** [comment]
Okay, I was not aware of the fact that you want the code actually depending more on OGGM...my long-term objective was actually to reach the opposite ;-) But on the other hand you are right, it's not a pain to get OGGM installed.
There is only one thing I don't yet understand (I'm curious so that I can take care of this in the future) : Why did you remove e.g. the flexibility in the bin size and the verbosity of the logging?

**Comment by fmaussion** [comment]
> Okay, I was not aware of the fact that you want the code actually depending more on OGGM...my long-term objective was actually to reach the opposite ;-) 

Indeed it would be cool, but under time pressure it just felt more easy and natural to do it (and test it) in OGGM for now (for me at least).

> There is only one thing I don't yet understand (I'm curious so that I can take care of this in the future) : Why did you remove e.g. the flexibility in the bin size 

Same argument: time. Right now I just wanted to get the same results as the RGI: more options mean more test, more documentation and more arguments to pass between function calls, and I didn't see much use in in the label part. Again, when this will be necessary then we can add it. (important programming rule: Only write code if you absolutely have to)

> and the verbosity of the logging?

I don't know. But  OGGM logs into files, which can be parsed and analyzed if necessary.

**Comment by jlandmann** [comment]
Well, ok, good to know what the background was!

**Comment by fmaussion** [comment]
@jlandmann just to clarify: most of your code now made it to the [simple_glacier_masks](https://github.com/OGGM/oggm/blob/85a929ca9832ebb66120065c8dd0affa2d7e8c6d/oggm/core/gis.py#L591). In particular. I took over your way to compute the masks (using rasterio) instead what I was using before (skimage).

What I added to the task:
- the other diagnostics for RGI (slope, aspect, median/min/max elev...)
- the "Glacier exterior" mask in order to make further diagnostics in the future (detect wrong geometries)
- tests (both in OGGM and in this repository)

What we would need to get rid of OGGM entirely:
- write the ``get_topo_file`` task in a dedicated package
- the automatic handling of errors and logging (using OGGM we catch and log all errors that occur in a file, which can be analyzed afterwards to track the source of the problem)
- multiprocessing (although this is of secondary interest I think)

All this is more trouble worth than necessary I think - do you agree? 

For the flexibility in the bin size: if needed it should be fairly straightforward to add. Do you need it?

**Comment by jlandmann** [comment]
Thanks for explaining again what you did!
Even if you had rejected my code I would have been okay, I was just a bit curious, because what I saw from your side went a bit into another direction than I understood from our mail/personal conversation or what my personal intention was.
To comment a bit your points from my view:

> write the `get_topo_file task` in a dedicated package

That was the idea of [geoget](https://github.com/OGGM/geoget), right? Apart from things that happened in the meanwhile in OGGM and provide an update to the function, this is already done.

> the automatic handling of errors and logging (using OGGM we catch and log all errors that occur in a file, which can be analyzed afterwards to track the source of the problem)

I really like the way OGGM handles errors, so I am totally fine with keeping this. My only thought was that if somebody uses rgitools as as standalone script, he might want to get more info on why some specific glaciers fail (e.g. because they are nominal glaciers) or get an idea of how many fail. But also this is probably a matter of taste.

> multiprocessing (although this is of secondary interest I think)

I'd call it luxury if you only want to process hypsometries, a "nice to have" if you want further processing.

I totally agree that especially the repetition of code is a problem when we want to uncouple rgitools from OGGM. So either we outsource stuff from OGGM completely and build only interfaces in OGGM or make supplementary packages like rgitools or geoget dependent on OGGM. Both solutions are fine for me, but probably it's also not a bad idea to keep some stuff OGGM-internal (i.e. user of rgitools installing OGGM vs. user of OGGM installing rgitools, geoget etc.).

> For the flexibility in the bin size: if needed it should be fairly straightforward to add. Do you need it?
I don't need it right now, my intention was again only to keep the application more flexible.

**Pull request merged**
